version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-deps-{{ checksum "TestWebPI.sln" }}
      - run:
          name: Install Dependencies
          command: dotnet restore
      - save_cache:
          paths:
            - ~/.nuget/packages
          key: dotnet-deps-{{ checksum "TestWebPI.sln" }}
      - run:
          name: Build Project
          command: dotnet build
      - run:
          name: Publish Project
          command: dotnet publish -c Debug -o ./artifacts
      - run:
          name: List DLLs in Artifacts Directory
          command: find ./artifacts -name "*.*"
      # 在这里添加部署到服务器的步骤，例如使用 SSH、FTP 或者其他部署方法
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
